name: apollon
channels:
  - conda-forge
  - defaults
dependencies:
  - adversarial-robustness-toolbox=1.18.1
  - django=5.1.3
  - jupyterlab=4.3.2
  - matplotlib=3.9.3
  - notebook=7.3.1
  - pandas=2.2.3
  - pip
  - python=3.11
  - scikit-learn=1.5.2
  - seaborn
